# Generated by Django 4.2.13 on 2024-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_stock_current_price_alter_stock_previous_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('AUD', 'AUD'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('HKD', 'HKD'), ('INR', 'INR'), ('INR', 'INR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MXN', 'MXN'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('RUB', 'RUB'), ('SEK', 'SEK'), ('SGD', 'SGD'), ('TRY', 'TRY'), ('USD', 'USD')], default='INR', max_length=3),
        ),
    ]
