# Generated by Django 4.2.13 on 2024-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_stock_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
