# Generated by Django 4.2.13 on 2024-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
