# Generated by Django 4.2.13 on 2024-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_stock_quantity_alter_transaction_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='previous_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_buy',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
