# Generated by Django 4.2.13 on 2024-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_current_price_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
